[package]
name = "natsuki"
version = "3.0.0"
authors = [
    "Chen-Pang He (https://jdh8.org)",
    "u/YourWrstNightmare (https://www.reddit.com/user/YourWrstNightmare)",
    "u/RoseQuartz6758 (https://www.reddit.com/user/RoseQuartz6758)",
]
edition = "2021"
description = "Discord bot named after Natsuki from Doki Doki Literature Club"
repository = "https://github.com/jdh8/natsuki"
license = "MIT"
category = "games"
keywords = ["discord", "ddlc"]

[dependencies]
anyhow = "1.0.75"
base64 = "0.21.3"
bitflags = "2.4.0"
chrono = "0.4.30"
csscolorparser = "0.6.2"
futures = "0.3.28"
image = "0.24.7"
md5 = "0.7.0"
poise = "0.5.5"
rand = "0.8.5"
regex = "1.9.5"
reqwest = "0.11.20"
serde_json = "1.0.105"
shuttle-poise = { git = "https://github.com/jdh8/shuttle", branch = "deploy" }
shuttle-runtime = { git = "https://github.com/jdh8/shuttle", branch = "deploy" }
shuttle-secrets = { git = "https://github.com/jdh8/shuttle", branch = "deploy" }
shuttle-static-folder = { git = "https://github.com/jdh8/shuttle", branch = "deploy" }
strum = { version = "0.25", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
tree_magic_mini = "3.0.3"
webp = "0.2.5"
